### ISSUE TITLE
調整 svg detect 方法

### ISSUE THREAD

**Issue by Rplus** [Rplus/resume#12]
try to use typeof SVGRect !== 'undefined' instead of Modernizr

順便也考慮是否可以略去 Modernizr lib

ref:
http://stackoverflow.com/a/28239372

**Comment by Rplus** [comment]
https://github.com/Rplus/resume/blob/master/app/styles/main.scss#L270

有其它地方會需要用到，暫時先留著 Modernizr
``` css
.no-js &,
.no-csstransforms & {
  bottom: 100%;
}
.csstransforms & {
  transform: translateY(-50%);
}
```
