### ISSUE TITLE
google font fallback for usability

### ISSUE THREAD

**Issue by Rplus** [Rplus/resume#4]
目前 `.say-hi` 用了 google font "Courgette",
css 設定為
```css
.hello .say-hi {
  font-family: 'Courgette',cursive;
}
```

並未設定 fallback 字型 ex: `sans-serif`
造成在 google font 載入前 `.say-hi` 都不會有字樣出現
